### ISSUE TITLE
Unable to run a full build from the root

### ISSUE THREAD

**Issue by jccarrillo** [CCI-MIT/XCoLab#2]
I'm unable to run a full build 'mvn clean install'
Steps to reproduce:
- delete maven repository (rm -Rf ~/.m2/repository)
- on project's root run 'mvn clean install'

The above failed to build.

**Comment by pdeboer** [comment]
Thanks for reporting and thanks for your pull request JC!

**Comment by jobachh** [comment]
Thanks for reporting this! We've made some changes to our build process and you can now build all binaries by running `mvn package` from the root of the repository.
